import pygame

pygame.init()

DEBUGMODE = True

MONITOR_INFO = pygame.display.Info()
WINDOW_WIDTH = MONITOR_INFO.current_w
WINDOW_HEIGHT = MONITOR_INFO.current_h

TILE_SIZE = min(WINDOW_WIDTH, WINDOW_HEIGHT) // 10
LEFT_SIDE_BUFFER = 150 # board buffer from left side of screen

BOARD_OFFSET_X = LEFT_SIDE_BUFFER
BOARD_OFFSET_Y = (WINDOW_HEIGHT - (TILE_SIZE * 8)) // 2

CAPTURE_BAR_WIDTH = TILE_SIZE * 6
CAPTURE_BAR_HEIGHT = TILE_SIZE/1.5
CAPTURE_BAR_X = BOARD_OFFSET_X #+ (TILE_SIZE*8-CAPTURE_BAR_WIDTH)/2

# White captures go near the bottom, Black captures go near the top
WHITE_CAPTURE_BAR_Y = WINDOW_HEIGHT - CAPTURE_BAR_HEIGHT/2 - BOARD_OFFSET_Y/2 
BLACK_CAPTURE_BAR_Y = -CAPTURE_BAR_HEIGHT/2 + BOARD_OFFSET_Y/2

PROMOTION_MENU_WIDTH = 400
PROMOTION_MENU_HEIGHT = 100
PROMOTION_MENU_X = (WINDOW_WIDTH - PROMOTION_MENU_WIDTH) // 2
PROMOTION_MENU_Y = (WINDOW_HEIGHT - PROMOTION_MENU_HEIGHT) // 2

GAME_OVER_WIDTH = 500
GAME_OVER_HEIGHT = 150
GAME_OVER_X = (WINDOW_WIDTH - GAME_OVER_WIDTH) // 2
GAME_OVER_Y = (WINDOW_HEIGHT - GAME_OVER_HEIGHT) // 2

PANEL_X = BOARD_OFFSET_X + TILE_SIZE*8 + 55
PANEL_Y = BOARD_OFFSET_Y+TILE_SIZE*2
ROW_HEIGHT = 28
COL_WIDTH = 75

hover_cooldown_start = None
hover_cooldown_duration = 150

ACTION_BTN_W = TILE_SIZE/1.2
ACTION_BTN_H = TILE_SIZE/1.8


RESIGN_BTN_X = CAPTURE_BAR_X + CAPTURE_BAR_WIDTH + (TILE_SIZE-ACTION_BTN_W)/2
DRAW_BTN_X = CAPTURE_BAR_X + CAPTURE_BAR_WIDTH + TILE_SIZE +(TILE_SIZE-ACTION_BTN_W)/2
ACTION_BTN_Y_WHITE = WHITE_CAPTURE_BAR_Y + (CAPTURE_BAR_HEIGHT - ACTION_BTN_H) / 2
ACTION_BTN_Y_BLACK = BLACK_CAPTURE_BAR_Y + (CAPTURE_BAR_HEIGHT - ACTION_BTN_H) / 2

LIGHT_SQUARE_COLOR = (234, 235, 239) #yk
DARK_SQUARE_COLOR = (134, 142, 151) #yk
SELECTED_HIGHLIGHT_COLOR = (159, 204, 239) #highlight for the square u selected
LAST_MOVE_HIGHLIGHT_COLOR = (159, 204, 239)
PREMOVE_HIGHLIGHT_COLOR = (176, 198, 232) #dot color for legal moves
CHECK_INDICATOR_COLOR = (240, 90, 90)


WHITE_PIECE_COLOR = (255, 255, 255)
WHITE_PIECE_OUTLINE = (0, 0, 0)
BLACK_PIECE_COLOR = (50, 50, 50)
BLACK_PIECE_OUTLINE = (200, 200, 200)